### ISSUE TITLE
Service Worker not being detected

### ISSUE THREAD

**Issue by messenjahofchrist** [pwa-builder/pwabuilder-api#98]
Hi,

After submitting my url in the builder, it's suggested that I add a service worker as it seems the one that I have is not detected. I have one on the root called sw.js. It is public. 

Am I not understanding something?

**Comment by JudahGabriel** [comment]
Hi @messenjahofchrist , can you open this bug over at [PWABuilder issues](https://github.com/pwa-builder/pwabuilder/issues)? We can discuss the issue there.

**Comment by messenjahofchrist** [comment]
@JudahGabriel sure, thanks!
